MetroCS/redistricting

.github/ISSUE_TEMPLATE/user-story.md

Added title to checklist.
Added Dependencies with sub-sections.
Reformatted template.

Update user-story.md with additional info

---

Vision.md

New pull request for vision file changes.
A new pull request was created because the original branch was based off of the wrong root.
This relates to Issue #1

Vision update2 based on master

---

src/swdmt/redistricting/AllDistrictGen.java
src/swdmt/redistricting/Redistrictor.java
src/swdmt/redistricting/RedistrictorTest.java
src/swdmt/redistricting/Region.java
src/swdmt/redistricting/StarGenerator.java

Created algorithm for issue #21 and also created test cases for the algorithm

Generate districts code

---

src/swdmt/redistricting/Region.java

Address UserStory #34 by providing access to voter information by the Region class.
Three staged commits: update versioning; correct existing Javadoc errors; add new method.

Add voters accessor

---

src/swdmt/redistricting/Party.java
src/swdmt/redistricting/PartyTest.java

Changed PartyTest.java and Party.java to accommodate change from UNAFFILIATED('*') to UNAFFILIATED('U')
See UserStory #41

Update Party.java to change UNAFFILIATED display char from '*' to 'U'

---

src/swdmt/redistricting/RedistrictingDriver.java
src/swdmt/redistricting/Renderer.java
src/swdmt/redistricting/RendererTest.java

Added Renderer utility class with methods to provide ASCII-graphics rendering of Region objects.
Addresses UserStory #33

Add basic ASCII-graphic rendering

---

src/swdmt/redistricting/AllDistrictGen.java

Checkstyle errors in AllDistrictGen have been resolved, see issue #30

CheckStyle errors for AllDistrictGen resolved

---

src/swdmt/redistricting/StarGenerator.java

Checkstyle errors concerning StarGenerator have been resolved, see issue #31

Errors in checkstyle for StarGenerator resolved

---

src/swdmt/redistricting/Redistrictor.java
src/swdmt/redistricting/Region.java
src/swdmt/redistricting/SnakingLocationComparer.java

Completed TODO as described in issue #22 "contiguity in generateDistricts"

Contiguity todo

---

src/swdmt/redistricting/AllDistrictGen.java

Reverts MetroCS/redistricting#46 to address Bug #49

Revert "CheckStyle errors for AllDistrictGen resolved"

---

src/swdmt/redistricting/StarGenerator.java

Reverts MetroCS/redistricting#45 to address Bug #49

Revert "Errors in checkstyle for StarGenerator resolved"

---

src/swdmt/redistricting/RendererTest.java

Test coverage of Renderer: statement 96%, branch 83%
Supports UserStory #33

RendererTest - additional tests and test-comment clarifications

---

src/swdmt/redistricting/District.java
src/swdmt/redistricting/DistrictTest.java

Resolves #60 
2 files changed:
District.java:
-Added functionality to distinguish if the district has non-contiguous regions with more then one 
adjacent location. 
DistrictTest.java:
-Added Tests to test the contiguityValid() method.

bug fix for coniguityValid() 

---

src/swdmt/redistricting/District.java

This pull request fixes Bug Issue #64

We have fixed the build error.

---

src/swdmt/redistricting/RegionTest.java

Making a pull request to add 2 more unit tests for issue #35. 1 test if the voter is outside the location, and the other is testing if the voter is in the location. Major commits are 1.

Unit tests for issue #35 - Region(Set<Location>,Set<Voter>)

---

Vision.md

Documentation to help clarify the intent and stakeholders of the project and product

Vision updates

---

Vision.md

Add subheading formatting within Scope section

Adjust formatting in Vision.md

---

src/swdmt/redistricting/Redistrictor.java

This edit is in response to issue #29. The issue identified the description as not being accurate to the functionality and has been changed.
Team: CS-3250-The-Collective

Edit to description for allDistrictsOfSpecificSize

---

src/swdmt/redistricting/VoterTest.java

- Solves #115 
- Changed the dependencies to be concurrent with Junit5
- Addition of comments for each test

Solution to #115, Updating VoterTest.java to Junit5

---

src/swdmt/redistricting/RedistrictorTest.java

Refactored [RedistrictorTest.java](https://github.com/MetroCS/redistricting/blob/master/src/swdmt/redistricting/RedistrictorTest.java) so that all test run on JUnit Jupiter and none run on Junit4.
Issue #117

Refactored RedistrictorTest.java Issue #117

---

src/swdmt/redistricting/RegionTest.java

Fixes #116 
- Addition of Tests
- Changing of the "Timeout" and "Throws" tests to work with junit5

Refactoring of RegionTest.java to be utilized by only Junit5 Jupiter

---

README.md
docs/examples/create_and_render_region.html

Create new example document with source code that demonstrates use of redistricting package utilities.
Add links in README for the published API and the new example.

Create usage example document and update README links

---

docs/examples/create_and_render_region.html

Included a transcript of a sample run of the example code. Added a footer to the page.

Add transcript to example

---

docs/examples/create_and_render_region.md

Create an MD version of the HTML file [docs/examples/create_and_render_region.html](https://github.com/MetroCS/redistricting/blob/eee4197a621f1dd085d3e24dec32377797fd29bd/docs/examples/create_and_render_region.html)

Convert example from HTML to MD

---

src/swdmt/redistricting/RegionTest.java

Added unit test for constructor Region(Collection<Voter>) to resolve issue https://github.com/MetroCS/redistricting/issues/119

Added Test for Region(Collection<Voter>)

---

build.xml

Resolves #153 
```
[jozu:msuod/cs3250/redistricting] jody% git branch -l
* master
userStory153
[jozu:msuod/cs3250/redistricting] jody% ant -p
Buildfile: msuod/cs3250/redistricting/build.xml
Build file for Redistricting project investigation
Main targets:
all          clean, generate documentation, analyze source code, run unit tests, check test coverage
checkstyle   generate checkstyle report
clean        clean up dynamically-created files and directories
coverage     Run unit tests with JaCoCo instrumentation and format results
cpd          proccess source with CPD
dist         Use ProGuard to create distribution jar
doc          generate usage documentation
doc-private  generate maintenance documentation
format       generate formatted versions of source code
jar          Creates a jar …
```

Removed run target and references to main class for issue #153

---

src/swdmt/redistricting/Renderer.java
src/swdmt/redistricting/RendererTest.java

- Resolves #95 
- Includes refactoring of existing code to utilize StringBuilder instead of String where appropriate

Render districts in text-graphic display of region per User Story #95

---

docs/examples/create_and_display_region.md

Example updated to demonstrate the text-graphic rendering of districts in the region display.

Updated example shows district rendering

---

src/metrocs/redistricting/Redistrictor.java
src/metrocs/redistricting/RedistrictorTest.java
src/metrocs/redistricting/SnakingLocationComparer.java
src/metrocs/redistricting/package-info.java

Integrated updated algorithm code from PR #149
- #149
Renamed redistricting method that utilizes the "snake" algorithm

Redistrictor update

---

src/metrocs/redistricting/StarGenerator.java

Here is the fix for issue #203. Below I have screen shots of the issue in the terminal before the fix and after the fix.

Fix for issue #203
